stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"

  acceptance:
    cfDeploy:
      strategy: "blue-green"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "361a1e92trial"
      space: "dev"
      credential: "cf-deploy-key"

  release:
    cfDeploy:
      strategy: "blue-green"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "361a1e92trial"
      space: "dev"
      credential: "cf-deploy-key"